Repository kubeflow/testing, pull requests merged in 2018-04, with the labels that each got.

#97 Update deploy
  dev-kubeflow-org/README.md
  dev-kubeflow-org/ks-app/.ksonnet/registries/incubator/40285d8a14f1ac5787e405e1023cf0c07f6aa28c.yaml
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/0003d9730d3300aa0aaeb5ebe6152dcf4f73fea9.yaml
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/cert-manager.jsonnet
  dev-kubeflow-org/ks-app/components/iap-ingress.jsonnet
  dev-kubeflow-org/ks-app/components/kubeflow-core.jsonnet
  dev-kubeflow-org/ks-app/components/params.libsonnet
  dev-kubeflow-org/ks-app/environments/base.libsonnet
  dev-kubeflow-org/ks-app/environments/default/main.jsonnet
  dev-kubeflow-org/ks-app/environments/default/params.libsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/k.libsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/k8s.libsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/swagger.json
  dev-kubeflow-org/recreate_app.sh
  dev-kubeflow-org/redeploy_app.sh
Labels: approved, lgtm, size/L

#98 add kubeflow_label.yml for label sycn across repos in kubeflow
  hack/label_generate/kubeflow_label_standard.csv
  hack/label_generate/process_label.py
  label_sync/README.md
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/L

#99 Update to v0.1.0-rc.4
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/20bdb46ee436b56fb9e3690d2a383b2afc8989f4.yaml
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/params.libsonnet
  dev-kubeflow-org/recreate_app.sh
Labels: approved, lgtm, size/S

#104 Add label sync cron job and add back label which has external dependency
  label_sync/cluster/label_sync_job.yaml
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/M

#107 Add dev doc for istio setup
  dev-kubeflow-org/README.md
Labels: approved, lgtm, size/S

#109 Replace kubeflow-images-staging with kubeflow-images-public
  README.md
  dev-kubeflow-org/ks-app/components/params.libsonnet
Labels: approved, lgtm, size/S

#110 Add junit-xml package to test image as this will be used to generate testing xml outputs
  images/Dockerfile
  images/Pipfile
  images/Pipfile.lock
Labels: approved, lgtm, size/L

#113 Add ssh to test-worker
  images/Dockerfile
Labels: approved, lgtm, size/XS

#114 Add pdmack to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#111 Create a new module: new_test_util
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/py_checks.py
  py/kubeflow/testing/test_helper.py
  py/kubeflow/testing/test_py_checks.py
  py/kubeflow/testing/test_py_lint.py
  workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL
