Repository kubeflow/testing, pull requests merged in 2018-05, with the labels that each got.

#117 Add jsonnet formatting test
  dev-kubeflow-org/ks-app/components/cert-manager.jsonnet
  dev-kubeflow-org/ks-app/components/iap-ingress.jsonnet
  dev-kubeflow-org/ks-app/components/issue-summarization-ui.jsonnet
  dev-kubeflow-org/ks-app/components/kubeflow-core.jsonnet
  dev-kubeflow-org/ks-app/environments/base.libsonnet
  dev-kubeflow-org/ks-app/environments/default/main.jsonnet
  dev-kubeflow-org/ks-app/environments/default/params.libsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/k.libsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/k8s.libsonnet
  py/kubeflow/testing/test_jsonnet_formatting.py
  test-infra/components/argo.jsonnet
  test-infra/components/argo.libsonnet
  test-infra/components/debug-worker.jsonnet
  test-infra/components/nfs-external.jsonnet
  test-infra/environments/kubeflow-ci/main.jsonnet
  test-infra/environments/kubeflow-ci/params.libsonnet
  test-infra/environments/releasing/.metadata/k.libsonnet
  test-infra/environments/releasing/.metadata/k8s.libsonnet
  test-infra/environments/releasing/main.jsonnet
  test-infra/environments/releasing/params.libsonnet
  test-infra/lib/v1.7.0/k.libsonnet
  test-infra/lib/v1.7.0/k8s.libsonnet
  test-infra/vendor/kubeflow/core/jupyterhub.libsonnet
  test-infra/vendor/kubeflow/core/prototypes/all.jsonnet
  workflows/components/workflows.jsonnet
  workflows/components/workflows.libsonnet
  workflows/lib/v1.7.0/k.libsonnet
  workflows/lib/v1.7.0/k8s.libsonnet
Labels: approved, lgtm, size/XXL

#118 Add exclude_dirs flag to test_jsonnet_formatting
  py/kubeflow/testing/test_jsonnet_formatting.py
Labels: approved, lgtm, size/S

#120 Move away from mlkube-testing to kubeflow-ci
  README.md
  py/kubeflow/testing/test-data/successful_workflow.yaml
  workflows/components/params.libsonnet
Labels: approved, lgtm, size/S

#119 Update test-infra argo component to v2.1.0
  test-infra/app.yaml
  test-infra/components/argo.jsonnet
  test-infra/components/argo.libsonnet
Labels: approved, lgtm, size/L

#121 Fix bytes literals in run() command
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#122 Added optional param replicas
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#123 Remove travis because we use prow for lint
  .travis.yml
Labels: approved, lgtm, size/S

#116 Small fixings in readme
  README.md
Labels: size/S

#126 Catch arbitrary exceptions in wait_for_workflows and log them so they
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#128 Move unittests to tests package
  py/kubeflow/testing/test_helper.py
  py/kubeflow/testing/test_py_checks.py
  py/kubeflow/testing/util.py
  py/kubeflow/tests/__init__.py
  py/kubeflow/tests/argo_client_test.py
  py/kubeflow/tests/prow_artifacts_test.py
  py/kubeflow/tests/run_e2e_workflow_test.py
  py/kubeflow/tests/test-data/successful_workflow.yaml
  py/kubeflow/tests/test_util_test.py
  py/kubeflow/tests/util_test.py
  workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#131 Update all.jsonnet
  test-infra/vendor/kubeflow/core/prototypes/all.jsonnet
Labels: approved, lgtm, size/XS

#130 Update dev.kubeflow.org
  dev-kubeflow-org/README.md
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/20bdb46ee436b56fb9e3690d2a383b2afc8989f4.yaml
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/fe9fc2aa3cceba6266ced46ee828ba21ee0152bd.yaml
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/cert-manager.jsonnet
  dev-kubeflow-org/ks-app/components/iap-ingress.jsonnet
  dev-kubeflow-org/ks-app/lib/v1.7.0/k8s.libsonnet
  dev-kubeflow-org/recreate_app.sh
  dev-kubeflow-org/redeploy_app.sh
Labels: approved, lgtm, size/L

#132 Image auto release -- testing repo part
  images/Dockerfile
  images/run_release.sh
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/M

#133 Add kunmingg as owner and reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#134 upgrade ksonnet to 0.10.2 in e2e Docker image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#138 Add a link to stackdriver logging for prow jobs to make it easier to get to the logs
  README.md
Labels: approved, lgtm, size/XS

#140 Fix gh-demo.kubeflow.org
  dev-kubeflow-org/ks-app/components/issue-summarization-ui.jsonnet
  dev-kubeflow-org/ks-app/components/params.libsonnet
Labels: approved, lgtm, size/L

#145 Label for sprint
  label_sync/cluster/label_sync_job.yaml
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/S

#146 Update ks-app for PVC changes
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/21550cace3f4b1ef68d21609236026aeb528a36d.yaml
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/cloud-endpoints.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/jupyterhub.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
Labels: approved, lgtm, size/M
