Repository kubeflow/testing, pull requests merged in 2018-07, with the labels that each got.

#167 Increase the timeout waiting for workflows to finish.
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#170 Use exponential backoff when getting the workflow status.
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/XS

#172 Increase the timeout when waiting for the workflows to 20 minutes.
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/XS

#174 Overhaul the way we upgrade dev.kubeflow.org
  dev-kubeflow-org/README.md
  dev-kubeflow-org/create_secrets.sh
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/cert-manager.jsonnet
  dev-kubeflow-org/ks-app/components/iap-ingress.jsonnet
  dev-kubeflow-org/ks-app/components/katib.jsonnet
  dev-kubeflow-org/ks-app/components/kubeflow-core.jsonnet
  dev-kubeflow-org/ks-app/components/params.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/ambassador.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/centraldashboard.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/echo-server.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/iap.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/jupyterhub.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/kubeform_spawner.py
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/metric-collector.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/all.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/echo-server.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/metric-collector.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/centraldashboard_test.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tf-job-operator.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/README.md
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/modeldb.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/prototypes/all.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/vizier.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/README.md
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/parts.yaml
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/prototypes/tf-job.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/tf-job.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/util.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-serving/tf-serving.libsonnet
  dev-kubeflow-org/redeploy_app.sh
  dev-kubeflow-org/upgrade_app.sh
Labels: approved, lgtm, size/XXL

#176 Add uuid-runtime package to worker
  images/Dockerfile
Labels: approved, lgtm, size/XS

#178 Fix the stackdriver link.
  README.md
Labels: approved, lgtm, size/XS

#180 Modify run_e2etest script to check for job_types and include_dirs
  README.md
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/L

#183 Copy artifacts should make the file names unique by appending a suffix.
  py/kubeflow/testing/prow_artifacts.py
  workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S
