Repository kubeflow/testing, pull requests merged in 2018-10, with the labels that each got.

#223 Compute postsubmit file diffs by PULL_BASE_SHA
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/S

#226 Don't consider modified_dirs for periodic jobs
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#228 Allow run_e2e_workflow to select which version of ks to use
  images/Dockerfile
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/M

#230 Fix gcs directory path for periodic Prow jobs
  deployment/kubeflow-latest_ks_app/vendor/kubeflow/katib@177377f154475e797ebf2c9bb7d156862f8e1231/prototypes/all.jsonnet
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/tests/prow_artifacts_test.py
Labels: approved, lgtm, size/S

#224 Fix the label sync
  label_sync/cluster/label_sync_cron_job.yaml
  label_sync/cluster/label_sync_job.yaml
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/L

#232 Fix label 0.4.0
  label_sync/README.md
  label_sync/cluster/label_sync_job.yaml
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/M

#236 Fix build of test worker image.
  images/Dockerfile
  images/Makefile
Labels: approved, lgtm, size/S

#237 add lib for e2e test
  images/Dockerfile
Labels: approved, lgtm, size/XS

#235 Add instructions for debugging tests where the container status isn't available
  README.md
Labels: approved, lgtm, size/M
