Repository kubeflow/testing, pull requests merged in 2018-09, with the labels that each got.

#201 upgrade ksonnet to 0.12.0 and jsonnet to 0.11.2
  images/Dockerfile
Labels: approved, lgtm, size/S

#203 Add a namespace argument
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#206 Fix retry logic in in argo_client
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/S

#211 Grant permissions to test service account to push to our public registry
  release-infra/kubeflow-images-public.iam.policy.yaml
Labels: approved, lgtm, size/XS

#200 Adding label for 0.4.0 as area/0.4.0
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/XS

#215 Recreate k8s client on auth failure
  py/kubeflow/testing/argo_client.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/util.py
  py/kubeflow/tests/argo_client_test.py
Labels: approved, lgtm, size/M

#216 Increase timeout in E2E workflow from 1 to 3 hours
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#217 Add log for why triggering a workflow
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#218 Enable workflow scoping for postsubmit jobs
  README.md
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/S

#219 Allow checkout.sh to process branch name
  images/checkout.sh
Labels: approved, lgtm, size/XS

#222 Ankush Signing Out
  OWNERS
Labels: approved, lgtm, size/XS
