Repository kubeflow/testing, pull requests merged in 2018-03, with the labels that each got.

#50 Create an initial OWNERS file.
  OWNERS
Labels: lgtm, size/S

#51 Upgrade Argo so we can use DAGs.
  test-infra/components/argo.libsonnet
Labels: approved, lgtm, size/XS

#47 Create a Docker image to use as our workers for releases.
  images/Makefile
  images/requirements.txt
Labels: approved, lgtm, size/M

#57 change testing-argo.kubeflow.io to testing-argo.kubeflow.org
  README.md
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#59 Fix Lun-kai github username
  OWNERS
Labels: approved, lgtm, size/XS

#61 Change test cluster from mlkube-testing to kubeflow-ci
  images/run_workflows.sh
Labels: approved, lgtm, size/XS

#62 fix argo uri
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#63 Fix typo in README
  README.md
Labels: approved, lgtm, size/S

#64 Upgrade ksonnet from 0.8 to 0.9 for testing image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#66 Run ks upgrade
  test-infra/app.yaml
  test-infra/environments/kubeflow-ci/spec.json
  test-infra/environments/prow/spec.json
  test-infra/environments/releasing/spec.json
  test-infra/lib/v1.7.0/k.libsonnet
  test-infra/lib/v1.7.0/k8s.libsonnet
  test-infra/lib/v1.7.0/swagger.json
  workflows/app.yaml
  workflows/environments/test/spec.json
  workflows/lib/v1.7.0/k.libsonnet
  workflows/lib/v1.7.0/k8s.libsonnet
  workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#65 Fix Dockerfile for testing image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#67 Print ksonnet version in tests
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#68 Add jsonnet to test-worker
  images/Dockerfile
  images/Makefile
Labels: approved, lgtm, size/S

#69 Make wait_for_deployment timeout configurable
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#56 Fix debug worker
  test-infra/components/debug-worker.jsonnet
  test-infra/components/params.libsonnet
  test-infra/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/XS

#73 Add the ability to specify arbitrary parameters in prow_config.yaml
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/prow_artifacts_test.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/run_e2e_workflow_test.py
  py/kubeflow/testing/test_util_test.py
  py/kubeflow/testing/util.py
  py/kubeflow/testing/util_test.py
Labels: approved, lgtm, size/L

#77 Check junit files for test status
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/S

#70 Poll for subprocess output while the process is running.
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/M

#76 Add ssh for minikube testing.
  images/Dockerfile
  images/Makefile
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/S

#74 Add information about debugging failed tests.
  README.md
Labels: approved, lgtm, size/M

#36 use pipenv in image building dockerfile
  images/Dockerfile
  images/requirements.txt
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/L

#83 Use userinfo.email scope with kube API Client
  README.md
  images/checkout.sh
  py/kubeflow/testing/util.py
  test-infra/components/debug-worker.jsonnet
Labels: approved, lgtm, size/S

#85 Upgrade to v1.10 for kubectl
  images/Dockerfile
Labels: approved, lgtm, size/XS

#93 Fix the ingress component for Argo.
  test-infra/app.yaml
  test-infra/components/argo.libsonnet
  test-infra/environments/kubeflow-ci/.metadata/k.libsonnet
  test-infra/environments/kubeflow-ci/.metadata/k8s.libsonnet
  test-infra/environments/kubeflow-ci/.metadata/swagger.json
  test-infra/environments/kubeflow-ci/main.jsonnet
  test-infra/environments/kubeflow-ci/params.libsonnet
  test-infra/environments/prow/.metadata/k.libsonnet
  test-infra/environments/prow/.metadata/k8s.libsonnet
  test-infra/environments/prow/.metadata/swagger.json
  test-infra/environments/prow/main.jsonnet
  test-infra/environments/prow/params.libsonnet
Labels: approved, lgtm, size/XXL

#94 Checkin dev.kubeflow.org ksonnet app into kubeflow/testing
  dev-kubeflow-org/.ksonnet/registries/incubator/40285d8a14f1ac5787e405e1023cf0c07f6aa28c.yaml
  dev-kubeflow-org/.ksonnet/registries/kubeflow/116a63e59869f9c1f5900317af79a4d198840d0b.yaml
  dev-kubeflow-org/README.md
  dev-kubeflow-org/app.yaml
  dev-kubeflow-org/components/cert-manager.jsonnet
  dev-kubeflow-org/components/iap-ingress.jsonnet
  dev-kubeflow-org/components/kubeflow-core.jsonnet
  dev-kubeflow-org/components/params.libsonnet
  dev-kubeflow-org/environments/base.libsonnet
  dev-kubeflow-org/environments/default/main.jsonnet
  dev-kubeflow-org/environments/default/params.libsonnet
  dev-kubeflow-org/lib/v1.7.0/k.libsonnet
  dev-kubeflow-org/lib/v1.7.0/k8s.libsonnet
  dev-kubeflow-org/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#80 Update README
  README.md
Labels: approved, lgtm, size/S
