Repository kubeflow/testing, pull requests merged in 2018-06, with the labels that each got.

#148 Catch and ignore exceptions in wait_for_workflows
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/XS

#151 Use logging.exception to log stacktrace
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_helper.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/S

#152 Ignore KeyError exception in argo_client.log_status
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/S

#153 Check if status and phase is set in argo workflow crd
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/XS

#156 Exclude all vendor directories from lint tests.
  py/kubeflow/testing/test_py_lint.py
Labels: approved, lgtm, size/XS

#155 Upgrade to ks 0.11 in our tests.
  images/Dockerfile
Labels: approved, lgtm, size/XS

#160 add area/inference label
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/XS

#159 Add katib to dev.kubeflow.org
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/katib.jsonnet
  dev-kubeflow-org/ks-app/components/params.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/modeldb.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/parts.yaml
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/prototypes/all.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/suggestion.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/vizier.libsonnet
  dev-kubeflow-org/recreate_app.sh
Labels: approved, lgtm, size/XL

#161 add instruction to update label sync
  label_sync/README.md
Labels: approved, lgtm, size/S

#157 Updates for d.k.o; based on ks 0.11.0; params added
  dev-kubeflow-org/ks-app/.gitignore
  dev-kubeflow-org/ks-app/.ksonnet/registries/kubeflow/21550cace3f4b1ef68d21609236026aeb528a36d.yaml
  dev-kubeflow-org/ks-app/app.yaml
  dev-kubeflow-org/ks-app/components/params.libsonnet
  dev-kubeflow-org/ks-app/environments/default/globals.libsonnet
  dev-kubeflow-org/ks-app/environments/default/main.jsonnet
  dev-kubeflow-org/ks-app/environments/default/params.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/ambassador.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/centraldashboard.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/configure_envoy_for_iap.sh
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/iap.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/jupyterhub.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/kubeform_spawner.py
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/all.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/prototypes/cloud-endpoints.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/setup_iap.sh
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/ambassador_test.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/centraldashboard_test.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tests/jupyterhub_test.jsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/core/tf-job-operator.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/katib/modeldb.libsonnet
  dev-kubeflow-org/ks-app/vendor/kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
  dev-kubeflow-org/recreate_app.sh
Labels: approved, lgtm, size/XL

#164 Add the filelock module.
  images/Dockerfile
Labels: approved, lgtm, size/XS

#165 Remove helm from cluster setup because we don't use it.
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/M
