Repository kubeflow/testing, pull requests merged in 2018-12, with the labels that each got.

#244 Upgrade daemonset file to 1.10
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#245 Change daemonset file to version 1.9
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#246 Use daemonset-preloaded yaml
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#251 Cleanup script should cleanup abandoned service accounts.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/L

#263 Use Cloud FileStore for the NFS share
  README.md
  test-infra/gcp_confgs/gcfs.yaml
  test-infra/ks_app/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  test-infra/ks_app/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  test-infra/ks_app/app.yaml
  test-infra/ks_app/components/argo.jsonnet
  test-infra/ks_app/components/argo.libsonnet
  test-infra/ks_app/components/debug-worker.jsonnet
  test-infra/ks_app/components/nfs-external.jsonnet
  test-infra/ks_app/components/params.libsonnet
  test-infra/ks_app/environments/base.libsonnet
  test-infra/ks_app/environments/kubeflow-ci/main.jsonnet
  test-infra/ks_app/environments/kubeflow-ci/params.libsonnet
  test-infra/ks_app/environments/releasing/.metadata/k.libsonnet
  test-infra/ks_app/environments/releasing/.metadata/k8s.libsonnet
  test-infra/ks_app/environments/releasing/.metadata/swagger.json
  test-infra/ks_app/environments/releasing/main.jsonnet
  test-infra/ks_app/environments/releasing/params.libsonnet
  test-infra/ks_app/lib/v1.7.0/k.libsonnet
  test-infra/ks_app/lib/v1.7.0/k8s.libsonnet
  test-infra/ks_app/lib/v1.7.0/swagger.json
  test-infra/ks_app/vendor/kubeflow/core/README.md
  test-infra/ks_app/vendor/kubeflow/core/jupyterhub.libsonnet
  test-infra/ks_app/vendor/kubeflow/core/nfs.libsonnet
  test-infra/ks_app/vendor/kubeflow/core/parts.yaml
  test-infra/ks_app/vendor/kubeflow/core/prototypes/all.jsonnet
  test-infra/ks_app/vendor/kubeflow/core/tf-job.libsonnet
Labels: approved, lgtm, size/M

#255 Properly compute the changed files in presubmits.
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/M
