Repository kubeflow/testing, pull requests merged in 2018-02, with the labels that each got.

#37 add env kubeflow-ci in test-infra
  test-infra/environments/kubeflow-ci/.metadata/k.libsonnet
  test-infra/environments/kubeflow-ci/.metadata/k8s.libsonnet
  test-infra/environments/kubeflow-ci/.metadata/swagger.json
  test-infra/environments/kubeflow-ci/main.jsonnet
  test-infra/environments/kubeflow-ci/params.libsonnet
  test-infra/environments/kubeflow-ci/spec.json
Labels: size/XXL

#41 Fix broken link, add newline to EOF
  README.md
Labels: size/XS

#48 Enable travis and do configurations
  .travis.yml
  images/Dockerfile
Labels: lgtm, size/S

#40 Add instructions for setting up infrastructure for releasing.
  README.md
  test-infra/components/argo.jsonnet
  test-infra/components/params.libsonnet
  test-infra/environments/kubeflow-ci/params.libsonnet
  test-infra/environments/releasing/.metadata/k.libsonnet
  test-infra/environments/releasing/.metadata/k8s.libsonnet
  test-infra/environments/releasing/.metadata/swagger.json
  test-infra/environments/releasing/main.jsonnet
  test-infra/environments/releasing/params.libsonnet
  test-infra/environments/releasing/spec.json
Labels: size/XXL
