Repository kubeflow/testing, pull requests merged in 2019-12, with the labels that each got.

#529 Gc instance groups based on usage
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#531 Add a GitHub action to add issues to needs triage kanban board.
  .github/workflows/triage_issues.yaml
Labels: approved, lgtm, size/S

#538 update Daemonset API for GPU driver installing
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#540 Moving go license tools from KFP repo
  py/kubeflow/testing/go-license-tools/README.md
  py/kubeflow/testing/go-license-tools/__init__.py
  py/kubeflow/testing/go-license-tools/concatenate_license.py
  py/kubeflow/testing/go-license-tools/get_github_license_info.py
  py/kubeflow/testing/go-license-tools/get_github_repo.py
  py/kubeflow/testing/go-license-tools/parse_toml_dep.py
  py/kubeflow/testing/go-license-tools/setup.py
Labels: approved, lgtm, size/XL

#551 Move over the KF cd pipelines into kubeflow/testing and refactor
  apps-cd/README.md
  apps-cd/pipelines/README.md
  apps-cd/pipelines/base/README.md
  apps-cd/pipelines/base/kustomization.yaml
  apps-cd/pipelines/base/pipeline.yaml
  apps-cd/pipelines/base/role-binding.yaml
  apps-cd/pipelines/base/service-account.yaml
  apps-cd/pipelines/base/task.yaml
  apps-cd/runs/README.md
  apps-cd/runs/profile_controller_v1795828.yaml
  py/kubeflow/testing/ci/rebuild-manifests.sh
Labels: approved, lgtm, size/XL
