Repository kubeflow/testing, pull requests merged in 2019-07, with the labels that each got.

#414 Fix postsubmit
  images/checkout.sh
  images/checkout_repos.sh
Labels: approved, lgtm, size/XS

#418 Fixbranch
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
  workflows/app.yaml
Labels: approved, lgtm, size/S

#419 set refs for newly fetched remote branch
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/XS

#420 Switch auto deploy to use v06 branch
  test-infra/auto-deploy/deploy-cron-v0-6.yaml
Labels: approved, lgtm, size/XS

#428 Add config for probot
  .github/stale.yml
Labels: approved, lgtm, ok-to-test, size/S
