Repository kubeflow/testing, pull requests merged in 2019-09, with the labels that each got.

#456 Define some labels that can be used to indicate estimated effort for an issue
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/S

#458 Add a flag to specify the depth to which to clone repos.
  images/checkout_repos.sh
Labels: approved, lgtm, size/S

#451 Support Python functions in workflows
  README.md
  prow_config.yaml
  py/kubeflow/testing/ci/__init__.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/L

#462 Cleanup SSL certificates in kubeflow-ci-deployment.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#463 Use a py_func and not ksonnet to define the unittest E2E workflow; update kf_unittests to create a valid workflow
  README.md
  prow_config.yaml
  py/kubeflow/testing/argo_build_util.py
  py/kubeflow/testing/argo_client.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/e2e_tool.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_py_checks.py
  py/kubeflow/testing/util.py
  workflows/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  workflows/app.yaml
  workflows/components/params.libsonnet
  workflows/components/workflows.jsonnet
  workflows/components/workflows.libsonnet
  workflows/environments/base.libsonnet
  workflows/environments/test/.metadata/k.libsonnet
  workflows/environments/test/.metadata/k8s.libsonnet
  workflows/environments/test/.metadata/swagger.json
  workflows/environments/test/main.jsonnet
  workflows/environments/test/params.libsonnet
  workflows/lib/v1.7.0/k.libsonnet
  workflows/lib/v1.7.0/k8s.libsonnet
  workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#466 Fix some issues with run_e2e_workflow.py and pyfunc
  hack/run_e2e_workflow_k8s_job.yaml
  py/kubeflow/testing/e2e_tool.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/L

#470 Upgrade kustomize from 2.0.3 to 3.2.0
  images/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#474 Improve cleanup of SSl certificates
  py/kubeflow/testing/argo_build_util.py
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M
