Repository kubeflow/testing, pull requests merged in 2019-11, with the labels that each got.

#512 cleanup_ci needs to use different expiration times for auto deployed and E2E clusters
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
  test-infra/cleanup-kubeflow-ci-deployment.yaml
Labels: approved, lgtm, size/L

#511 Add a method to build checkout repos dictionary
  py/kubeflow/testing/util.py
  py/kubeflow/tests/util_test.py
Labels: approved, lgtm, size/M

#514 Add a utility routine to wait for a batch job to finish.
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/M

#516 Start a playbook for the buildcop that focuses on keeping tests healthy.
  buildcop.md
Labels: approved, lgtm, size/M

#513 Update get credentials to work with new auto deploy naming schema
  py/kubeflow/testing/get_kf_testing_cluster.py
  py/kubeflow/tests/get_kf_testing_cluster_test.py
Labels: approved, lgtm, size/L

#519 get-credential needs to activate service account
  py/kubeflow/testing/get_kf_testing_cluster.py
Labels: approved, lgtm, size/S

#523 bulk_deploy support v0.6
  codelabs/setup-codelab-project.yaml
  py/kubeflow/testing/bulk_deploy.py
  py/kubeflow/testing/create_unique_kf_instance.py
Labels: approved, lgtm, size/L

#521 Codelabs scripts
  codelabs/move_kubeflow_projects_into_folder.sh
  codelabs/setup_kubeflow_folder.sh
Labels: approved, lgtm, size/M

#522 Kubeflow autodeploy jobs need to use kubeflow/kfctl
  py/kubeflow/testing/create_unique_kf_instance.py
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/S

#526 Add pattern to match e2e test disk
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
Labels: approved, lgtm, size/XS
