Repository kubeflow/testing, pull requests merged in 2019-04, with the labels that each got.

#344 Update auto-deploy infrastructure to use the new kfctl binary.
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/deploy-cron-v0-5.yaml
  test-infra/auto-deploy/deploy-master.yaml
  test-infra/ks_app/components/cleanup-ci-cron.jsonnet
  test-infra/ks_app/components/cleanup-ci.jsonnet
  test-infra/ks_app/components/cleanup-ci.libsonnet
Labels: approved, lgtm, size/L

#349 Updated test artifacts to report repos in finished/metadata
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/tests/prow_artifacts_test.py
Labels: approved, lgtm, size/S

#351 add devices label
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/XS

#352 Update cronjob to deploy testing clusters to kubeflow-ci-deployment
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/auto_deploy.sh
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-5.yaml
Labels: approved, lgtm, size/M

#353 Undelete endpoint service for testing cluster.
  py/kubeflow/testing/create_kf_instance.py
Labels: approved, lgtm, size/S

#354 get_kf_testing_cluster
  py/kubeflow/testing/get_kf_testing_cluster.py
  py/kubeflow/tests/get_kf_testing_cluster_test.py
  py/kubeflow/tests/test-data/README.md
  py/kubeflow/tests/test-data/deploymentmanager-v2.json
Labels: approved, lgtm, size/XXL

#359 Fix cleanup_ci.py - fix cleanup of argo workflows and IAM policy bindings
  OWNERS
  images/Dockerfile
  images/gcb_build/image_build.json
  py/kubeflow/testing/cleanup_ci.py
  test-infra/ks_app/components/cleanup-ci.libsonnet
Labels: approved, lgtm, size/M

#363 Argo workflows's should stick around for a week or so.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/XS

#360 Upload workflow status as Prow artifacts
  README.md
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, ok-to-test, size/M

#369 Add bazel installation to ci-work image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#365 Add fire, gitpython and hub to test image and fix namespace packaging
  images/Dockerfile
  images/Makefile
  images/checkout_repos.sh
  images/gcb_build/image_build.json
  images/setup_ssh.sh
  py/kubeflow/__init__.py
  py/kubeflow/testing/test_py_lint.py
Labels: approved, lgtm, size/L

#370 add kustomize for test_worker image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#371 upgrade test image go version to 1.12
  images/Dockerfile
Labels: approved, lgtm, size/XS

#376 Improve the documentation for debugging tests.
  README.md
Labels: approved, lgtm, size/M
