Repository kubeflow/testing, pull requests merged in 2019-05, with the labels that each got.

#356 Report for test flakiness
  scripts/Flakiness_report.ipynb
Labels: approved, lgtm, ok-to-test, size/XXL

#378 Use the injected base branch env var
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, ok-to-test, size/S

#377 Upload workflow status while timeout
  py/kubeflow/testing/argo_client.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, ok-to-test, size/M

#381 Fixed typos and some clarification on playbook doc
  playbook.md
  test-infra/ks_app/environments/kubeflow-ci/params.libsonnet
Labels: approved, lgtm, size/M

#382 GC backend services in kubeflow-ci-deployment
  py/kubeflow/testing/cleanup_ci.py
  test-infra/ks_app/components/cleanup-ci-cron.jsonnet
  test-infra/ks_app/components/cleanup-ci.libsonnet
Labels: approved, lgtm, size/M

#384 Create OWNERS for py/kubeflow
  py/kubeflow/OWNERS
Labels: approved, lgtm, size/XS

#385 Fetch remote branches in E2E test
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/S

#387 add zabbasi to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#388 Update cleanup ci cron
  py/kubeflow/testing/cleanup_ci.py
  test-infra/ks_app/components/cleanup-ci-cron.jsonnet
  test-infra/ks_app/components/cleanup-ci.libsonnet
Labels: approved, lgtm, size/S

#383 Fix the playbook.
  playbook.md
  test-infra/ks_app/environments/kubeflow-ci/params.libsonnet
Labels: approved, lgtm, size/S

#389 Add gabrielwen & zhenghuiwang to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#390 Cleanup all ingress resources
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/L

#392 Aggressively cleanup failed deployments.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/S

#395 Retry on 504 GATEWAY_TIMEOUT
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/S

#394 improvements to README.md
  README.md
Labels: approved, lgtm, size/XS

#397 Fix cleanup disks
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/S

#398 Fix retry on gateway timeout (#306)
  py/kubeflow/testing/argo_client.py
Labels: approved, lgtm, size/M

#399 Add cmake to testing worker image
  images/Dockerfile
Labels: approved, lgtm, size/XS
