Repository kubeflow/testing, pull requests merged in 2019-02, with the labels that each got.

#302 Add step to setup secret in test infra setup
  README.md
Labels: approved, lgtm, size/S

#300 Create a cron job to regularly garbage collect test resources.
  py/kubeflow/testing/cleanup_ci.py
  test-infra/ks_app/components/cleanup-ci-cron.jsonnet
  test-infra/ks_app/components/cleanup-ci.jsonnet
  test-infra/ks_app/components/cleanup-ci.libsonnet
  test-infra/ks_app/components/params.libsonnet
Labels: approved, lgtm, size/L

#303 upgrade test worker to go1.11
  images/Dockerfile
Labels: approved, lgtm, size/XS

#305 fix gcb issue
  images/Makefile
  images/gcb_build/image_build.json
  images/image_build.jsonnet
Labels: approved, lgtm, size/M

#297 Github repositories snapshot and checkout.
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Pipfile
  test-infra/auto-deploy/Pipfile.lock
  test-infra/auto-deploy/checkout.sh
  test-infra/auto-deploy/checkout_lib/__init__.py
  test-infra/auto-deploy/checkout_lib/checkout_util.py
  test-infra/auto-deploy/checkout_lib/repo_clone_snapshot.py
  test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py
  test-infra/auto-deploy/deploy-cron.yaml
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/workflows.sh
Labels: approved, lgtm, size/XL

#307 add mercurial to test image
  images/Dockerfile
  images/gcb_build/image_build.json
Labels: approved, lgtm, size/XS

#306 Fix label_sync by running on an admin cluster.
  admin-infra/README.md
  admin-infra/cluster.jinja
  admin-infra/cluster.yaml
  label_sync/README.md
Labels: approved, lgtm, size/L

#309 Document how to Use the new stackdriver agents in our test cluster.
  README.md
Labels: approved, lgtm, size/M

#308 Add snapshot timestamp to cluster labels and use it to select deploying cluster
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Pipfile
  test-infra/auto-deploy/Pipfile.lock
  test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py
  test-infra/auto-deploy/deploy-cron.yaml
  test-infra/auto-deploy/deployment-workflows.sh
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/lib-args.sh
  test-infra/auto-deploy/workflows.sh
Labels: approved, lgtm, size/L

#311 Add cron job to clean outdated disks
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#312 Fix cron format
  test-infra/auto-deploy/deploy-cron.yaml
Labels: approved, lgtm, size/XS

#313 Deploy testing cluster for both master and v0-4
  test-infra/auto-deploy/checkout-snapshot.sh
  test-infra/auto-deploy/checkout_lib/repo_clone_snapshot.py
  test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-4.yaml
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/lib-args.sh
Labels: approved, lgtm, size/L

#296 Add Seldon component to kf-v0.4 cluster
  py/kubeflow/testing/create_kf_instance.py
Labels: approved, lgtm, size/XS

#317 Add TLS certification after creating cluster
  images/Dockerfile
  py/kubeflow/testing/create_kf_instance.py
Labels: approved, lgtm, size/S

#322 Adopting Python pkgutil-style namespacing
  py/kubeflow/__init__.py
Labels: approved, lgtm, size/XS

#319 clean up unused bindings in iam
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/tests/cleanup_ci_test.py
  py/kubeflow/tests/test-data/iam_bindings.yaml
Labels: approved, lgtm, size/L
