Repository kubeflow/testing, pull requests merged in 2019-06, with the labels that each got.

#402 Use git shallow clone
  images/checkout.sh
  images/checkout_repos.sh
Labels: approved, lgtm, size/XS

#401 Add a custom exception wrapping workflow results
  py/kubeflow/testing/argo_client.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/util.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, lgtm, size/L

#404 Add method to clean up HTTP proxies
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#408 Use Kustomize and Istio for auto deployment
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/XS

#409 Fix auto deployment
  py/kubeflow/testing/create_kf_instance.py
Labels: approved, lgtm, size/XS

#410 Add JDK8 to testing worker image
  images/Dockerfile
Labels: approved, lgtm, size/XS

#411 If get merge-base fails; keep going don't abort
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/S
