Repository kubeflow/testing, pull requests merged in 2019-03, with the labels that each got.

#320 Create a batch job to allow manual runs of auto-deploying the latest code
  test-infra/auto-deploy/Makefile
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-4.yaml
  test-infra/auto-deploy/deploy-master.yaml
  test-infra/auto-deploy/deployment-workflows.sh
  test-infra/auto-deploy/init.sh
Labels: approved, lgtm, size/L

#318 Automate new project creation
  project_creation/README.md
  project_creation/apis.py
  project_creation/config.yaml
  project_creation/project.py
  project_creation/project.py.schema
  project_creation/service-accounts.py
Labels: approved, lgtm, size/XL

#323 Improve auto_deploy to support changing zone and testing changes.
  images/gcb_build/image_build.json
  py/kubeflow/testing/create_kf_instance.py
  py/kubeflow/testing/util.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Makefile
  test-infra/auto-deploy/auto_deploy.sh
  test-infra/auto-deploy/checkout-snapshot.sh
  test-infra/auto-deploy/checkout_lib/checkout_util.py
  test-infra/auto-deploy/checkout_lib/repo_clone_snapshot.py
  test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-4.yaml
  test-infra/auto-deploy/deploy-master.yaml
  test-infra/auto-deploy/deployment-workflows.sh
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/lib-args.sh
  test-infra/auto-deploy/set_images.sh
  test-infra/ks_app/components/nfs-external.jsonnet
Labels: approved, lgtm, size/XL

#327 Fix repo spec for 0.4 auto-deploy cron job.
  test-infra/auto-deploy/deploy-cron-v0-4.yaml
Labels: approved, lgtm, size/XS

#325 Update project creation
  project_creation/README.md
  project_creation/config.yaml
Labels: approved, lgtm, size/S

#330 Cleanup firewall rules.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/L

#329 Improve instructions for getting logs for failed runs.
  README.md
Labels: approved, lgtm, size/M

#336 Fix an issue with wait_for_deployment; handle case ready_replicas is None
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#339 Fix for presubmits: append last 4 digits of build number
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#338 Add a playbook for dealing with cleaning up the test infrastructure.
  playbook.md
  py/kubeflow/testing/cleanup_ci.py
  test-infra/ks_app/components/cleanup-ci.libsonnet
Labels: approved, lgtm, size/M

#340 Fix cleanup_ci exception
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/S

#341 Fix bug in wait for statefulset; handle ready replicas is None.
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#347 Fix NFS volume mounting; the NFS was recreated but still using the old IP
  playbook.md
  test-infra/ks_app/environments/kubeflow-ci/params.libsonnet
Labels: approved, lgtm, size/L
