Repository kubeflow/testing, pull requests merged in 2019-01, with the labels that each got.

#272 Add richardsliu as OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#271 ksonnet utilities for testing.
  py/kubeflow/testing/ks_util.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/M

#261 Python script to cleanup argo and services (cloud endpoints)
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/L

#274 Support ksonnet apps using 0.3.0 spec in our tests.
  images/Dockerfile
  py/kubeflow/testing/ks_util.py
Labels: approved, lgtm, size/S

#258 Add instructions about how to write Argo workflows for E2E tests.
  README.md
Labels: approved, lgtm, size/L

#241 Improve readability of priority/p1 and status/icebox labels
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/XS

#253 Add labels for CUJs and cleanup some labels.
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/M

#278 Add pytest to the test image.
  images/Pipfile
Labels: approved, lgtm, size/XS

#281 Make util.run py3 compatible.
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/S

#283 Upgrade Argo to v2.2.1 so we can use TTLAfterSeconds option to GC old workflows
  test-infra/ks_app/app.yaml
  test-infra/ks_app/components/argo.jsonnet
  test-infra/ks_app/lib/ksonnet-lib/v1.7.0/k.libsonnet
  test-infra/ks_app/lib/ksonnet-lib/v1.7.0/k8s.libsonnet
  test-infra/ks_app/lib/ksonnet-lib/v1.7.0/swagger.json
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/README.md
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/jupyterhub.libsonnet
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/nfs.libsonnet
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/parts.yaml
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/prototypes/all.jsonnet
  test-infra/ks_app/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/tf-job.libsonnet
Labels: approved, lgtm, size/S

#286 Add retry block to kfctl apply all
  py/kubeflow/testing/create_kf_instance.py
Labels: approved, lgtm, size/S

#287 auto deployment cronjob
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Pipfile
  test-infra/auto-deploy/Pipfile.lock
  test-infra/auto-deploy/checkout.sh
  test-infra/auto-deploy/deploy-cron.yaml
  test-infra/auto-deploy/workflows.sh
Labels: approved, lgtm, size/XL

#279 Update the pipfile.lock file to include pytest
  images/.gitignore
  images/Makefile
  images/Pipfile
  images/Pipfile.lock
  images/image_build.jsonnet
Labels: approved, lgtm, size/L

#290 Upgrade argo ui image to work around bug with logs not showing up.
  test-infra/ks_app/components/argo.jsonnet
  test-infra/ks_app/components/argo.libsonnet
  test-infra/ks_app/components/params.libsonnet
Labels: approved, lgtm, size/M

#291 Show Argo workflow URLs when test starts.
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/tests/prow_artifacts_test.py
Labels: approved, lgtm, size/S

#289 Test utilities for CRDs.
  images/build/image_build.json
  py/kubeflow/testing/ks_util.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/L

#293 Improve the cleanup of Kubeflow deployments.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#294 Update auto deploy to be runnable on kubeflow-ci.
  py/kubeflow/testing/create_kf_instance.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/deploy-cron.yaml
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/workflows.sh
Labels: approved, lgtm, size/M

#285 Fixed missing quotes in echo statement
  deployment/redeploy_app.sh
Labels: approved, lgtm, ok-to-test, size/XS

#298 Use snapshot files to checkout repositories.
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/checkout-snapshot.sh
  test-infra/auto-deploy/init.sh
  test-infra/auto-deploy/repo-clone-snapshot.py
Labels: approved, lgtm, size/L
