Repository kubeflow/testing, pull requests merged in 2019-08, with the labels that each got.

#430 Fix periodic tests checkout script
  images/checkout.sh
Labels: approved, lgtm, size/XS

#436 Recreate the NFS share to fix out of space
  OWNERS
  images/gcb_build/image_build.json
  playbook.md
  test-infra/ks_app/environments/kubeflow-ci/params.libsonnet
Labels: approved, lgtm, size/M

#441 Fix auto-deployment from master
  py/kubeflow/testing/create_kf_instance.py
  py/kubeflow/testing/util.py
  test-infra/auto-deploy/auto_deploy.sh
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-6.yaml
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/L

#449 Revert "Support Python functions in workflows"
  prow_config.yaml
  py/kubeflow/testing/ci/__init__.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/L

#452 Updating issue bot configs
  release-infra/kf-releasing/.cache/master/.github/issue_label_bot.yaml
Labels: approved, lgtm, ok-to-test, size/XS
