Repository kubeflow/testing, pull requests merged in 2019-10, with the labels that each got.

#477 fix wait_for_deployment to also check for apps/v1 deployments
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XS

#481 Fix bugs with cleanup of deployments and clusters
  playbook.md
  py/kubeflow/testing/cleanup_ci.py
  test-infra/cleanup-kubeflow-ci-deployment.yaml
Labels: approved, lgtm, size/L

#484 Pass an empty body to getIamPolicy
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/XS

#485 Aggressively GC clusters that are in an error state.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/M

#487 Check environment variable BUILD_ID and use that for the prow bucket.
  py/kubeflow/testing/prow_artifacts.py
Labels: approved, lgtm, size/S

#488 Fix bucket where artifacts are uploaded to
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/e2e_tool.py
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_py_lint.py
Labels: approved, lgtm, size/M

#486 Clean up SSL certificate based on domain
  py/kubeflow/testing/cleanup_ci.py
  test-infra/cleanup-kubeflow-ci-deployment.yaml
Labels: approved, lgtm, size/L

#490 Support subdirectories for junit files and junit_class_name
  README.md
  package-lock.json
  py/kubeflow/testing/argo_build_util.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/conftest.py
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_py_lint.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XL

#493 Revert "Support subdirectories for junit files and grouping in test grid by name (#490)
  README.md
  package-lock.json
  py/kubeflow/testing/argo_build_util.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/conftest.py
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_py_lint.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XL

#472 autodeploy jobs should pull kfdef specs from kubeflow/manifests
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/XS

#494 Revert "Revert "Support subdirectories for junit files and grouping in test grid by name (#490)" (#493)"
  README.md
  package-lock.json
  py/kubeflow/testing/argo_build_util.py
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/conftest.py
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/test_py_lint.py
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/XL

#497 util check_secret
  py/kubeflow/testing/util.py
Labels: approved, lgtm, size/S

#500 upgrade kubectl to v1.14.0 in test-worker
  images/Dockerfile
Labels: approved, lgtm, size/XS

#503 Clone additional repos in prow config python paths
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#495 Auto deploy job needs to use the new kfctl syntax.
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/create_kf_instance.py
  py/kubeflow/testing/create_unique_kf_instance.py
  py/kubeflow/testing/util.py
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/L

#504 Fix conditions for checking out additional repos
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#505 Fix the destination path for checking out repos
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, lgtm, size/XS

#506 Fix auto-deployment labels to be valid GCP labels.
  py/kubeflow/testing/create_unique_kf_instance.py
  test-infra/auto-deploy/deploy-master.yaml
Labels: approved, lgtm, size/S
