Repository kubeflow/testing, pull requests merged in 2020-06, with the labels that each got.

#673 Apps CD scripts need to be updated to work with kustomize refactor
  apps-cd/applications.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#675 Add retries to GCP blueprint deployment for webhook.cert-manager.io errors
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, lgtm, size/XS

#674 Add sourceRepo in apps-cd/applications.yaml
  apps-cd/applications.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#680 Auto update for xgboost image tag in manifests
  apps-cd/applications.yaml
Labels: approved, lgtm, ok-to-test, size/S

#681 Create a tekton pipeline to run go unittests.
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_go-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/namespace.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/service-account-kf-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_go-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  docs/argo.md
  docs/tekton.md
  images/Dockerfile.py3
  images/skaffold.yaml
  prow_config.yaml
  py/kubeflow/testing/tekton_client.py
  tekton/README.md
  tekton/runs/README.md
  tekton/runs/dummy-teardown-run.yaml
  tekton/runs/go-test-run.yaml
  tekton/runs/nb-test-run.yaml
  tekton/templates/installs/kf-ci/kustomization.yaml
  tekton/templates/pipelines/go-test-pipeline.yaml
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kustomization.yaml
  tekton/testing/README.md
  tests/README.md
  tests/go.mod
  tests/validate_test.go
Labels: approved, lgtm, size/XL

#683 Tekton pipeline client should use generate name
  py/kubeflow/testing/prow_artifacts.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/tekton_client.py
  py/kubeflow/testing/util.py
  tekton/runs/go-test-run.yaml
  tekton/templates/tasks/go-tests.yaml
Labels: approved, lgtm, size/L

#687 Update tekton.md
  docs/tekton.md
Labels: approved, lgtm, size/XS

#690 Update tekton.md
  docs/tekton.md
Labels: approved, lgtm, size/XS

#686 Fix a bug in tekton_client.py
  py/kubeflow/testing/tekton_client.py
Labels: approved, lgtm, size/M

#689 Apps CD scripts need to be updated to work with kustomize refactor
  apps-cd/applications.yaml
Labels: approved, lgtm, size/S

#692 Fix apps CD; install jinja2 library
  apps-cd/README.md
  apps-cd/latest_image.json
  apps-cd/pipelines/base/config/app-pipeline.template.yaml
  apps-cd/pipelines/base/kustomization.yaml
  apps-cd/requirements.txt
  py/kubeflow/testing/cd/update_kf_apps.py
Labels: approved, lgtm, size/M

#691 Create a task and pipeline to check IAP endpoint and KF app deployements
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  images/Dockerfile.py3
  images/README.md
  images/latest_images.json
  tekton/templates/pipelines/gcp-kf-ready.yaml
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XL

#694 Create a v1.1.0 config in Apps CD scripts
  apps-cd/applications.yaml
Labels: approved, lgtm, size/M

#698 * Use a newer docker image for the gounitests to fix
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  images/README.md
  images/latest_image.json
  images/latest_images.json
  tekton/runs/dummy-teardown-run.yaml
  tekton/runs/go-test-run.yaml
  tekton/templates/dummy-teardown-task.yaml
  tekton/templates/installs/auto-deploy/kustomization.yaml
  tekton/templates/installs/kf-ci/kustomization.yaml
  tekton/templates/pipelines/deploy-gcp-blueprint-pipeline.yaml
  tekton/templates/pipelines/gcp-kf-ready.yaml
  tekton/templates/pipelines/go-test-pipeline.yaml
  tekton/templates/pipelines/notebook-test-pipeline.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/L

#697 Fix periodic runs of tekton workflows.
  apps-cd/README.md
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/tekton_client.py
Labels: approved, cla: yes, lgtm, size/M

#699 Remove Googlers no longer working on Kubeflow.
  OWNERS
  py/kubeflow/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#705 let kpt set value in upstream/manifests/stacks/gcp
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, cla: yes, lgtm, size/XS

#703 Revamp how Tekton pipelines to run notebooks work.
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  go/cmd/nomos-wait/go.mod
  go/cmd/nomos-wait/go.sum
  go/cmd/nomos-wait/main.go
  go/cmd/nomos-wait/main_test.go
  images/Dockerfile.py3
  images/README.md
  images/latest_image.json
  notebook_testing/Dockerfile.notebook_runner
  notebook_testing/README.md
  py/kubeflow/testing/notebook_tests/conftest.py
  py/kubeflow/testing/notebook_tests/execute_notebook.py
  py/kubeflow/testing/notebook_tests/job.yaml
  py/kubeflow/testing/notebook_tests/nb_test_util.py
  py/kubeflow/testing/notebook_tests/run_notebook_test.py
  py/kubeflow/testing/tekton_client.py
  py/kubeflow/testing/util.py
  tekton/runs/go-test-run.yaml
  tekton/runs/nb-test-run.yaml
  tekton/templates/pipelines/notebook-test-pipeline.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#706 Use zonal cluster for gcp blueprint
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, cla: yes, lgtm, size/XS

#704 GCP endpoint ready test needs to set the name of the cluster
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  py/kubeflow/testing/get_kf_testing_cluster.py
  py/kubeflow/tests/get_kf_testing_cluster_test.py
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
Labels: approved, cla: yes, lgtm, size/L

#709 ACM should point at kubeflowt/testing/master
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/auto-deploy.yaml
  test-infra/kf-ci-v1/configsync/config-management.yaml
Labels: approved, cla: yes, lgtm, size/L

#710 Fix copy-artifacts step in mnist notebook tests.
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  docs/tekton.md
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/S

#711 Update the worker image in tekton pipelines
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  images/latest_image.json
  tekton/runs/nb-test-run.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/M
