Repository kubeflow/testing, pull requests merged in 2020-10, with the labels that each got.

#757 chore: add new label area/kfp/aws-sagemaker-components
  label_sync/acm_repo/namespaces/batch_v1beta1_cronjob_label-sync-cron.yaml
  label_sync/acm_repo/namespaces/~g_v1_configmap_label-sync-v2-g8d5bm2m78.yaml
  label_sync/kubeflow_label.yml
Labels: approved, cla: yes, lgtm, size/S

#755 AWS Init Support for Kuberflow/Testing
  images/Dockerfile.py3.aws
  images/aws-scripts/OWNERS
  images/aws-scripts/check-load-balancer-status.sh
  images/aws-scripts/create-eks-cluster.sh
  images/aws-scripts/delete-eks-cluster.sh
  images/aws-scripts/deploy-kubeflow.sh
  images/aws-scripts/uninstall-kubeflow.sh
  images/run_workflows.sh
  py/kubeflow/testing/cloudprovider/aws/OWNERS
  py/kubeflow/testing/cloudprovider/aws/__init__.py
  py/kubeflow/testing/cloudprovider/aws/prow_artifacts.py
  py/kubeflow/testing/cloudprovider/aws/util.py
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, cla: yes, lgtm, size/XXL

#761 Fix python3.8 and pip linking
  images/Dockerfile.py3
  images/Dockerfile.py3.aws
Labels: approved, cla: yes, lgtm, size/S

#763 Add OWNERS files for Shared Assets
  images/OWNERS
  py/kubeflow/testing/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#765 Add support to check if ingress is ready
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, lgtm, size/M

#766 Upgrade CNRM in Kubeflow ci management from 1.9 to 1.27.2
  test-infra/management/instance/cnrm-install-system/0-cnrm-system.yaml
  test-infra/management/instance/cnrm-install-system/crds.yaml
Labels: approved, cla: yes, lgtm, size/XXL
