Repository kubeflow/testing, pull requests merged in 2020-05, with the labels that each got.

#646 Remove applications.py; commonLabels should be immutable.
  py/kubeflow/testing/tools/applications.py
Labels: approved, lgtm, size/M

#649 Fix paths to license tool scripts
  py/kubeflow/testing/go-license-tools/README.md
Labels: approved, lgtm, size/XS

#648 Delete setup scripts for KCC.
  config_connector/README.md
  config_connector/community_cluster_setup.sh
  config_connector/config_connector_setup.sh
  config_connector/containercluster.yaml
  config_connector/containernodepool.yaml
  config_connector/iampolicy.yaml
  config_connector/iamserviceaccount.yaml
  config_connector/serviceaccount.yaml
Labels: approved, lgtm, size/L

#651 Fix cleanup certificates.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/XS

#652 A simple python script to deploy Kubeflow using the GCP blueprint.
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
  py/kubeflow/testing/create_kf_instance.py
  test-infra/management/instance/cnrm-install-kubeflow-ci-deployment/per-namespace-components.yaml
  test-infra/management/instance/cnrm-install-kubeflow-ci-deployment/service_account.yaml
Labels: approved, lgtm, size/L

#653 Create a Tekton pipeline to deploy using the GCP blueprint.
  acm-repo/README.md
  acm-repo/namespaces/auto-deploy/namespace.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test.yaml
  acm-repo/system/README.md
  acm-repo/system/repo.yaml
  docs/tekton.md
  images/Dockerfile.py3
  tekton/templates/Makefile
  tekton/templates/README.md
  tekton/templates/installs/auto-deploy/kustomization.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/kustomization.yaml
  tekton/templates/tasks/notebook-test-task.yaml
  test-infra/auto-deploy/manifest/deploy_blueprint_pipeline.yaml
  test-infra/management/README.md
  test-infra/management/instance/cnrm-install-kubeflow-ci-deployment/role-bindings.yaml
Labels: approved, lgtm, size/L

#655 Code and jobs to cleanup the the new auto-deployed blueprints.
  acm-repo/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repo/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-4bm54d2bmb.yaml
  playbook/README.md
  py/kubeflow/testing/cleanup_blueprints.py
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cnrm_clients.py
  py/kubeflow/testing/create_context.py
  tekton/templates/Makefile
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/kustomization.yaml
  test-infra/README.md
  test-infra/cleanup/Makefile
  test-infra/cleanup/README.md
  test-infra/cleanup/cleanup-blueprints-pipeline.yaml
  test-infra/cleanup/cleanup-ci-cronjob.yaml
  test-infra/cleanup/kustomization.yaml
Labels: approved, lgtm, size/XL

#657 Support blueprints in autodeployment.
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_deploy-gcp-blueprint.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  py/kubeflow/testing/auto_deploy/blueprint_reconciler.py
  py/kubeflow/testing/auto_deploy/blueprint_reconciler_test.py
  py/kubeflow/testing/auto_deploy/reconciler.py
  py/kubeflow/testing/auto_deploy/server.py
  py/kubeflow/testing/auto_deploy/test_data/example-pipeline-run.yaml
  py/kubeflow/testing/auto_deploy/util.py
  py/kubeflow/testing/blueprints/__init__.py
  py/kubeflow/testing/blueprints/util.py
  py/kubeflow/testing/cleanup_blueprints.py
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
  py/kubeflow/testing/gcp_util.py
  py/kubeflow/testing/gcp_util_test.py
  py/kubeflow/testing/tekton_cr_clients.py
  tekton/templates/installs/auto-deploy/kustomization.yaml
  tekton/templates/pipelines/deploy-gcp-blueprint-pipeline.yaml
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Dockerfile.skaffold
  test-infra/auto-deploy/README.md
  test-infra/auto-deploy/manifest/config/deployments.yaml
  test-infra/auto-deploy/manifest/config/pipeline-run-deploy-blueprint-master.yaml
  test-infra/auto-deploy/manifest/deploy_blueprint_pipeline.yaml
  test-infra/auto-deploy/manifest/deployment.yaml
  test-infra/auto-deploy/manifest/kustomization.yaml
  test-infra/auto-deploy/skaffold.yaml
  test-infra/auto-deploy/templates/index.html
Labels: approved, lgtm, size/XXL

#661 Fix auto-deployments reconciler.
  py/kubeflow/testing/auto_deploy/reconciler.py
  py/kubeflow/testing/delete_kf_instance.py
Labels: approved, lgtm, size/S

#662 Fix cluster get-credentials command in playbook
  README.md
  playbook/playbook.md
Labels: approved, lgtm, size/XS

#663 Fix cleanup_ci.py; remove references to blueprints.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/S

#665 Cleanup orphaned backend services and instance groups.
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
  py/kubeflow/testing/gcp_util.py
Labels: approved, lgtm, size/L

#671 Define kfserving area labels
  label_sync/kubeflow_label.yml
Labels: approved, lgtm, size/S

#670 Use multiple ACM repos and create a code-intelligence cluster.
  acm-repo/cluster/tekton.yaml
  acm-repo/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repo/namespaces/auto-deploy/namespace.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_deploy-gcp-blueprint.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repo/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test.yaml
  acm-repo/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-4bm54d2bmb.yaml
  acm-repo/namespaces/tekton-pipelines/namespace.yaml
  acm-repo/namespaces/tekton-pipelines/release-0.12.yaml
  acm-repos/README.md
  acm-repos/kf-ci-management/README.md
  acm-repos/kf-ci-management/clusterregistry/kf-ci-selector.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/compute.cnrm.cloud.google.com_v1beta1_computeaddress_code-intelligence-ip.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/compute.cnrm.cloud.google.com_v1beta1_computedisk_code-intelligence-storage-artifact-store.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/compute.cnrm.cloud.google.com_v1beta1_computedisk_code-intelligence-storage-metadata-store.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containercluster_code-intelligence.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containernodepool_code-intelligence-cpu-pool-v1.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-bigquery.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-cloudbuild.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-cloudsql.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-dataflow.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-dataproc.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-istio-wi.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-logging.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-metricwriter.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-ml.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-monitoringviewer.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-network.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-servicemanagement.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-source.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-storage.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-viewer.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-admin-wi.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-bigquery.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-cloudbuild.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-cloudsql.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-dataflow.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-dataproc.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-logging.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-metricwriter.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-ml.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-monitoringviewer.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-source.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-storage.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-user-viewer.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-logging.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-policy-cloudtrace.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-policy-meshtelemetry.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-policy-monitoring-viewer.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-policy-monitoring.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-vm-policy-storage.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_code-intelligence-admin.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_code-intelligence-user.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_code-intelligence-vm.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/namespace.yaml
  acm-repos/kf-ci-management/system/README.md
  acm-repos/kf-ci-management/system/repo.yaml
  test-infra/management/configsync/config-management.yaml
Labels: approved, lgtm, size/XXL
