Repository kubeflow/testing, pull requests merged in 2020-01, with the labels that each got.

#553 Update go-license-tool
  py/kubeflow/testing/go-license-tools/README.md
  py/kubeflow/testing/go-license-tools/patch_additional_license_info.py
Labels: approved, lgtm, size/L

#555 Fix errors in go licensing tool README
  py/kubeflow/testing/go-license-tools/README.md
Labels: approved, lgtm, size/XS

#559 Create a python script to autogenerate PipelineRun's for all kubeflow applications
  .pylintrc
  apps-cd/README.md
  apps-cd/applications.yaml
  apps-cd/runs/app-pipeline.template.yaml
  py/kubeflow/testing/cd/__init__.py
  py/kubeflow/testing/cd/test_data/notebook_controller.expected.yaml
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/cd/update_kf_apps_test.py
  py/kubeflow/testing/ci/rebuild-manifests.sh
  py/kubeflow/testing/py_lint_test.py
Labels: approved, lgtm, size/XL

#561 update_kf_apps.py should create pipelineruns for images that need to be updated.
  apps-cd/applications.yaml
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/cd/update_kf_apps_test.py
Labels: approved, lgtm, size/L

#564 Create a Kubernetes deployment to continuously run update_kf_apps for CD
  apps-cd/Dockerfile
  apps-cd/README.md
  apps-cd/applications.yaml
  apps-cd/pipelines/base/deployment.yaml
  apps-cd/pipelines/base/kustomization.yaml
  apps-cd/run_with_auto_restart.py
  apps-cd/skaffold.yaml
  apps-cd/update_launcher.py
  py/kubeflow/testing/cd/update_kf_apps.py
Labels: approved, lgtm, size/L

#566 Fix cleanup logic for IAM policy bindings
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
Labels: approved, lgtm, size/M

#567 Fix context for notebook-controller.
  apps-cd/applications.yaml
Labels: approved, lgtm, size/XS

#568 Revert "Fix cleanup logic for IAM policy bindings (#566)"
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
Labels: lgtm, size/M

#569 Add tool and guide for getting python license information
  py/kubeflow/testing/python-license-tools/README.md
  py/kubeflow/testing/python-license-tools/pipfile_to_github_repo.py
Labels: approved, lgtm, size/L

#570 Fix cleanup logic for IAM policy bindings.
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
  py/kubeflow/testing/test_data/trim_bindings.input.yaml
  py/kubeflow/tests/cleanup_ci_test.py
  test-infra/cleanup-kubeflow-ci-deployment.yaml
Labels: approved, lgtm, size/L

#572 Define a v0.8 release
  apps-cd/Dockerfile
  apps-cd/applications.yaml
  apps-cd/pipelines/base/deployment.yaml
  apps-cd/pipelines/base/kustomization.yaml
  apps-cd/pipelines/base/task.yaml
  apps-cd/runs/app-pipeline.template.yaml
  apps-cd/skaffold.yaml
  images/README.md
  images/skaffold.yaml
  py/kubeflow/testing/cd/create_manifests_pr.py
  py/kubeflow/testing/cd/image_util.py
  py/kubeflow/testing/cd/image_util_test.py
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/ci/rebuild-manifests.sh
Labels: approved, lgtm, size/XL

#586 Only keep the 3 most recent auto deployments for each version.
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/cleanup_ci_test.py
  py/kubeflow/testing/create_unique_kf_instance.py
  py/kubeflow/testing/test_data/cleanup_deployments.yaml
Labels: approved, lgtm, size/XXL

#583 Update playbook for dealing with NFS out of space and use kustomize.
  playbook.md
  test-infra/base/kustomization.yaml
  test-infra/base/nfs-external.yaml
  test-infra/base/pvc.yaml
  test-infra/base/statefulset.yaml
  test-infra/ks_app/components/debug-worker.jsonnet
  test-infra/ks_app/components/nfs-external.jsonnet
Labels: approved, lgtm, size/L

#575 Cicd delete old prs
  apps-cd/Dockerfile
  apps-cd/README.md
  apps-cd/applications.yaml
  apps-cd/pipelines/base/config/app-pipeline.template.yaml
  apps-cd/pipelines/base/deployment.yaml
  apps-cd/pipelines/base/kustomization.yaml
  apps-cd/pipelines/base/task.yaml
  apps-cd/pipelines/overlays/dev/deployment.yaml
  apps-cd/pipelines/overlays/dev/kustomization.yaml
  apps-cd/pipelines/overlays/prod/kustomization.yaml
  apps-cd/requirements.txt
  apps-cd/runs/README.md
  apps-cd/runs/profile_controller_v1795828.yaml
  apps-cd/skaffold.yaml
  apps-cd/update_launcher.py
  images/skaffold.yaml
  py/kubeflow/testing/cd/close_old_prs.py
  py/kubeflow/testing/cd/create_manifests_pr.py
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/py_lint_test.py
  py/kubeflow/testing/tools/secret_creator.py
  py/kubeflow/testing/yaml_util.py
Labels: approved, lgtm, size/XXL

#588 [Node][License] Introduced Node-License CLI
  py/kubeflow/testing/node-license-tools/.gitignore
  py/kubeflow/testing/node-license-tools/README.md
  py/kubeflow/testing/node-license-tools/_esm_entrypoint.js
  py/kubeflow/testing/node-license-tools/commands/getLicenseInfo.js
  py/kubeflow/testing/node-license-tools/node_lic.js
  py/kubeflow/testing/node-license-tools/package-lock.json
  py/kubeflow/testing/node-license-tools/package.json
Labels: approved, area/front-end, lgtm, priority/p0, size/XXL

#587 Add TFJob and PyTorch controller to the list of applications for CD.
  apps-cd/applications.yaml
  apps-cd/pipelines/base/config/app-pipeline.template.yaml
  apps-cd/pipelines/base/pipeline.yaml
  apps-cd/pipelines/base/task.yaml
  apps-cd/pipelines/overlays/dev/deployment.yaml
  py/kubeflow/testing/cd/test_data/notebook_controller.expected.yaml
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/cd/update_kf_apps_test.py
  py/kubeflow/testing/kf_logging.py
Labels: approved, lgtm, size/L
