Repository kubeflow/testing, pull requests merged in 2020-03, with the labels that each got.

#617 Fix a bug in clenaup_ci preventing GC'ing of deployments.
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/XS

#619 Fix autodeploy job
  py/kubeflow/testing/auto_deploy/reconciler.py
  py/kubeflow/testing/auto_deploy/reconciler_test.py
  py/kubeflow/testing/auto_deploy/test_data/completed_job.yaml
Labels: approved, lgtm, size/L

#620 Add README for auto-deploy v2
  py/kubeflow/testing/auto_deploy/README.md
  test-infra/auto-deploy/README.md
  test-infra/auto-deploy/deploy-cron-master.yaml
  test-infra/auto-deploy/deploy-cron-v0-6.yaml
  test-infra/auto-deploy/deploy-master.yaml
  test-infra/auto-deploy/deploy-v0-6.yaml
  test-infra/auto-deploy/lib-args.sh
  test-infra/auto-deploy/manifest/config/deployments.yaml
  test-infra/auto-deploy/set_images.sh
Labels: approved, lgtm, size/L

#621 Tekton init
  py/kubeflow/testing/get_kf_testing_cluster.py
  tekton/configs/virtual-service.yaml
  tekton/templates/notebook-test-task.yaml
Labels: approved, lgtm, size/L

#623 Added gsoc label to kubeflow_label.yml
  label_sync/kubeflow_label.yml
Labels: approved, area/kfctl, lgtm, size/XS

#625 Use Anthos Config Management to continually sync the label config to the cluster
  label_sync/README.md
  label_sync/acm_repo/README.md
  label_sync/acm_repo/namespaces/batch_v1beta1_cronjob_label-sync-cron.yaml
  label_sync/acm_repo/namespaces/github-admin/github-admin.yaml
  label_sync/acm_repo/namespaces/~g_v1_configmap_label-sync-v2-89b54b7724.yaml
  label_sync/acm_repo/system/README.md
  label_sync/acm_repo/system/repo.yaml
  label_sync/cluster/label_sync_cron_job.yaml
  label_sync/hydrate.sh
  label_sync/kubeflow_label.yml
  label_sync/kustomization.yaml
  label_sync/label_sync_acm_config.yaml
Labels: approved, lgtm, size/L

#525 KCC setup
  config_connector/README.md
  config_connector/community_cluster_setup.sh
  config_connector/config_connector_setup.sh
  config_connector/containercluster.yaml
  config_connector/containernodepool.yaml
  config_connector/iampolicy.yaml
  config_connector/iamserviceaccount.yaml
  config_connector/serviceaccount.yaml
Labels: approved, lgtm, size/L

#632 Fix casing for GitHub references
  py/kubeflow/testing/go-license-tools/README.md
  py/kubeflow/testing/go-license-tools/get_github_license_info.py
  py/kubeflow/testing/python-license-tools/README.md
Labels: approved, lgtm, ok-to-test, size/S

#633 Update README to reflect Kubeflow migration to prow build cluster
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/S
