Repository kubeflow/testing, pull requests merged in 2020-11, with the labels that each got.

#767 A simple program to GC old resources like Tekton pipelineruns
  go/cmd/cleanup/cleanup_pipelineruns.yaml
  go/cmd/cleanup/main.go
  go/cmd/cleanup/types/types.go
  go/go.mod
  go/go.sum
  playbook/playbook.md
Labels: approved, cla: yes, lgtm, size/XL

#771 Run tekton py unittests pipeline
  .pylintrc
  prow_config.yaml
  py/kubeflow/testing/auto_deploy/blueprint_reconciler_test.py
  py/kubeflow/testing/auto_deploy/reconciler_test.py
  py/kubeflow/testing/cleanup_ci.py
  py/kubeflow/testing/get_kf_testing_cluster.py
  py/kubeflow/testing/run_e2e_workflow.py
  py/kubeflow/testing/tekton_client.py
  py/kubeflow/testing/util.py
  py/kubeflow/tests/prow_artifacts_test.py
  py/kubeflow/tests/run_e2e_workflow_test.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#759 Update set values tests
  py/kubeflow/testing/ci/kf_unittests.py
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#775 Revert Code Change
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, cla: yes, lgtm, size/M

#781 Grant access to the labelbot projects to my personal account.
  Makefile
  acm-repos/kf-ci-management/namespaces/github-probots/iam-policy-members.yaml
  acm-repos/kf-ci-management/namespaces/github-probots/namespace.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iampolicy-member-jeremylewi.yaml
Labels: approved, cla: yes, lgtm, size/M

#778 Create individual pipeline from pipelinerun to make it reusable
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-test.yaml
  prow_config.yaml
  tekton/runs/py-test-run.yaml
  tekton/runs/py-unittests-run.yaml
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/pipelines/py-unittests-pipeline.yaml
  tekton/templates/tasks/py-lint.yaml
  tekton/templates/tasks/py-test.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#783 Fix ingress check issue
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, lgtm, size/XS

#782 Update management ACM config
  test-infra/management/configsync/config-management.yaml
Labels: approved, cla: yes, lgtm, size/XS

#792 Grant myself IAP access.
  acm-repos/kf-ci-management/namespaces/github-probots/iam-policy-members.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iampolicy-member-jeremylewi.yaml
Labels: approved, cla: yes, lgtm, size/M

#795 chore: update OWNERS
  OWNERS
  py/kubeflow/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#796 test: pin gcp blueprint auto deploy to v1.1 branch in testing repo
  test-infra/auto-deploy/manifest/config/pipeline-run-deploy-blueprint-v1.1.yaml
Labels: approved, cla: yes, lgtm, size/XS

#797 test: include cleanup cronjob in acm repos
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-4bm54d2bmb.yaml
  test-infra/cleanup/Makefile
Labels: approved, cla: yes, lgtm, size/M

#798 test(gcp): fix cleanup_blueprints
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-dh2846bbg5.yaml
  py/kubeflow/testing/cleanup_blueprints.py
  test-infra/cleanup/cleanup-blueprints-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/S

#799 test(gcp): cleanup blueprints - fix3
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_deployment_auto-deploy-server.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_auto-deploy-config-7f4chh5g64.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-556b6f2hdb.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  py/kubeflow/testing/cleanup_blueprints.py
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  test-infra/cleanup/cleanup-blueprints-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/M

#800 test(gcp): fix cleanup minor mistakes
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
Labels: approved, cla: yes

#801 test(gcp): fix cleanup_blueprints.py one more attempt
  py/kubeflow/testing/cleanup_blueprints.py
  py/kubeflow/testing/cnrm_clients.py
  py/requirements.txt
Labels: approved, cla: yes, lgtm, size/S

#804 Create v1.2.0 config
  apps-cd/applications.yaml
Labels: approved, cla: yes, lgtm, size/S

#803 Upgrade Python K8s Client SDK version to 12.0.0
  .gitignore
  images/Dockerfile.py3
  images/Dockerfile.py3.aws
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, lgtm, size/M

#806 Change daemonset succeed condition
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, size/XS

#808 Add a workload identity binding for the emojichat namespace
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-emojichat-wi.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#794 Update py unittest
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-test.yaml
  tekton/runs/py-test-run.yaml
  tekton/templates/pipelines/py-unittests-pipeline.yaml
  tekton/templates/tasks/py-lint.yaml
  tekton/templates/tasks/py-test.yaml
Labels: approved, cla: yes, lgtm, size/L

#809 Fix the service account for emoji chat
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_code-intelligence-emojichat-wi.yaml
Labels: approved, cla: yes, lgtm, size/XS

#810 Define the issue-label-bot GCP SA in CNRM.
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_issue-label-bot-user.yaml
Labels: approved, cla: yes, lgtm, size/XS

#813 feat: set up cronjob that cleans up old tekton resources for kf-releasing
  go/Dockerfile.cleanup
  go/Makefile
  go/cmd/cleanup/configs/cleanup_pipelineruns_kf_ci.yaml
  go/cmd/cleanup/configs/cleanup_pipelineruns_kf_releasing.yaml
  release-infra/cleanup/cleanup-pipelineruns-cronjob.yaml
  release-infra/cleanup/cluster-role-binding.yaml
  release-infra/cleanup/cluster-role.yaml
  release-infra/cleanup/kustomization.yaml
  release-infra/cleanup/service-account.yaml
Labels: approved, cla: yes, lgtm, size/L

#816 test(gcp): revert set values commands for kubeflow package
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, cla: yes, lgtm, size/S

#817 Add reusable scripts to kubeflow/testing
  hack/cherry-picks.md
  hack/cherry_pick_pull.sh
Labels: approved, cla: yes, lgtm, size/L

#819 test: fix notebook_runner dockerfile
  notebook_testing/Dockerfile.notebook_runner
Labels: approved, cla: yes, lgtm, size/XS

#820 test: fix notebook-test task
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/XS

#821 test(gcp): update acm repo
  acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_deployment_auto-deploy-server.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-blueprints.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-ci-kubeflow-ci-deployment.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/batch_v1beta1_cronjob_cleanup-pipelineruns.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_go-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_py-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/v1_configmap_auto-deploy-config-2hg564b6ck.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/v1_configmap_cleanup-config-ghbg4c2kmk.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/v1_service_auto-deploy-server.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/v1_service_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_cleanup-config-556b6f2hdb.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_gcp-kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_go-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-lint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_py-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/v1_service_test-pod.yaml
Labels: approved, cla: yes, size/L

#822 test(gcp): fix acm repo sync
  Makefile
  acm-repos/kf-ci-v1/namespaces/kf-ci/~g_v1_service_test-pod.yaml
  test-infra/cleanup/Makefile
Labels: approved, cla: yes, size/S

#818 fix(pylint,pytest): detect failures and error message associated with the task
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_py-unittests.yaml
  py/kubeflow/testing/tekton_client.py
  py/kubeflow/testing/test_helper.py
  tekton/templates/pipelines/py-unittests-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/M

#824 test(kfp): kfp standalone cluster for testing
  Makefile
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containercluster_kfp-standalone-1.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containernodepool_kfp-standalone-1-nodepool.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-logging.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring-viewer.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-storage.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_kfp-standalone-1-vm.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/namespace.yaml
  gcp/packages/README.md
  gcp/packages/cluster-standard/Kptfile
  gcp/packages/cluster-standard/Makefile
  gcp/packages/cluster-standard/README.md
  gcp/packages/cluster-standard/cluster.yaml
  gcp/packages/cluster-standard/iam/iam.yaml
  gcp/packages/cluster-standard/iam/kustomization.yaml
  gcp/packages/cluster-standard/kustomization.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/README.md
  test-infra/kfp/kfp-standalone-1/Kptfile
  test-infra/kfp/kfp-standalone-1/Makefile
  test-infra/kfp/kfp-standalone-1/README.md
  test-infra/kfp/kfp-standalone-1/cluster.yaml
  test-infra/kfp/kfp-standalone-1/iam/iam.yaml
  test-infra/kfp/kfp-standalone-1/iam/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomization.yaml
Labels: approved, cla: yes, size/XL

#826 test(gcp): update kfp-standalone-1 labels
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containercluster_kfp-standalone-1.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/container.cnrm.cloud.google.com_v1beta1_containernodepool_kfp-standalone-1-nodepool.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-logging.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring-viewer.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-monitoring.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_kfp-standalone-1-vm-policy-storage.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/iam.cnrm.cloud.google.com_v1beta1_iamserviceaccount_kfp-standalone-1-vm.yaml
  test-infra/kfp/kfp-standalone-1/instance/kustomization.yaml
Labels: approved, cla: yes, size/S
