Repository kubeflow/testing, pull requests merged in 2020-12, with the labels that each got.

#830 test(kfp): enable GKE service for kfp-ci project
  Makefile
  acm-repos/kf-ci-management/namespaces/kfp-ci/serviceusage.cnrm.cloud.google.com_v1beta1_service_container.googleapis.com.yaml
  gcp/packages/cluster-standard/upstream/services/enable-services.yaml
  gcp/packages/cluster-standard/upstream/services/kustomization.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/upstream/services/enable-services.yaml
  test-infra/kfp/kfp-standalone-1/upstream/services/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#828 test(kfp): use staging proxy instead
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml
Labels: approved, cla: yes, lgtm, size/S

#831 test(kfp): update KFP endpoint to staging
  test-infra/kfp/Makefile
  test-infra/kfp/endpoint
Labels: approved, cla: yes, lgtm

#832 test(gcp): fix kf-ci-v1 permissions on kubeflow-ci-deployment project
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/namespace.yaml
  acm-repos/kf-ci-management/namespaces/kubeflow-ci-deployment/rolebinding-kf-ci-v1-cnrm-admin.yaml
Labels: approved, cla: yes, lgtm, size/S

#833 test(kfp): add ci-team@kubeflow.org as owner for kfp-ci project
  acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/iam/iam.yaml
Labels: approved, cla: yes, lgtm, size/S

#835 test(kfp): grant prow sa permission to access kfp-standalone-1
  acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/iam/Kptfile
  test-infra/kfp/iam/iam.yaml
Labels: approved, cla: yes, lgtm, size/M

#836 Add Doc and GitOps resources for Optional-Test-Infra
  README.md
  aws/Doc/architecture.md
  aws/Doc/onboarding.md
  aws/GitOps/README.md
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/katib-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/kfctl-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/kfserving-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/manifests-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pytorch-operator-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/testing-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/Makefile
  aws/OWNERS
  aws/Picture/GenericArgoWorkflow.png
  aws/Picture/OptionalTestInfra_CurrentDesign.png
  aws/Picture/OptionalTestInfra_FutureDesign.png
  aws/README.md
  aws/User/README.md
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/katib-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/kfctl-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/kfserving-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/manifests-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/pytorch-operator-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/testing-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, lgtm, size/XL

#837 Fix bad file name
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/Makefile
Labels: approved, cla: yes, size/XS

#838 Add more doc for optional-test-infra and PR template
  .github/pull_request_template.md
  aws/Doc/architecture.md
  aws/Doc/onboarding.md
  aws/README.md
  aws/User/README.md
Labels: cla: yes, size/M

#840 Add installation manifests for optional-test-infra
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/katib-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/kfctl-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/kfserving-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/manifests-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pytorch-operator-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/testing-repo.yaml
  aws/Makefile
  aws/User/README.md
  aws/User/clusters/kubeflow-shared-test-infra-poc-argo/namespaces/argo/installs/argo-starter.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-pipelines/installs/tekton-pipelines-starter.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/katib-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/kfctl-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/kfserving-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/manifests-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/pytorch-operator-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/testing-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/installs/prow-starter.yaml
Labels: approved, cla: yes, size/XXL
