Repository kubeflow/testing, pull requests merged in 2020-07, with the labels that each got.

#712 Fix bugs in GCP blueprint tests
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/M

#713 Fix get-credentials; To support debugging of the test worker image deploy a stateful set that is in sync with the worker image
  acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_statefulset_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_service_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/apps_v1_statefulset_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/~g_v1_service_test-pod.yaml
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/pipelines/test-pod.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/L

#716 Directory for junit file for notebooks is incorrect
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  tekton/templates/pipelines/notebook-test-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS

#714 Create a go binary to wrap the shell commands to create PRs.
  go/Dockerfile.prctl
  go/Makefile
  go/cmd/prctl/main.go
  go/go.mod
  go/go.sum
  go/prctl_latest_image.json
  go/skaffold.yaml
Labels: approved, cla: yes, lgtm, size/XL

#718 Bug fixes and improvements to prctl
  go/Dockerfile.prctl
  go/cmd/prctl/main.go
  go/cmd/prctl/main_test.go
  go/go.mod
  go/prctl_latest_image.json
Labels: approved, cla: yes, lgtm, size/L

#719 prctl can use a GitHub App to create PRs.
  go/Dockerfile.prctl
  go/cmd/prctl/main.go
  go/go.mod
  go/go.sum
  go/pkg/ghrepo/repo.go
  go/prctl_latest_image.json
Labels: approved, cla: yes, lgtm, size/L

#700 Add pingsutw to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#717 Bug: NameError: global name 'FileNotFoundError' is not defined
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, cla: yes, lgtm, size/XS

#720 prctl should support using urls for the flag --repo
  go/cmd/prctl/main.go
  go/pkg/ghrepo/repo.go
  go/pkg/ghrepo/repo_test.go
  go/prctl_latest_image.json
Labels: approved, cla: yes, lgtm, size/M

#722 Fix notebook test
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_pipeline_notebook-test.yaml
  tekton/templates/pipelines/notebook-test-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS

#724 Recreate the NFS share because we ran out of space.
  test-infra/base/pvc.yaml
Labels: approved, cla: yes, lgtm, size/XS

#726 Start auto-deploying the GCP blueprints v1.1 branch
  acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_deployment_auto-deploy-server.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/~g_v1_configmap_auto-deploy-config-2778d8c6c8.yaml
  test-infra/auto-deploy/manifest/config/pipeline-run-deploy-blueprint-v1.1.yaml
  test-infra/auto-deploy/manifest/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#727 Update tests to work with Kubernetes 1.16
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, lgtm, size/S

#728 Fix bug in notebook task
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/XS

#729 Update Dockerfile.py3
  images/Dockerfile.py3
Labels: approved, cla: yes, lgtm, size/M

#731 Fix workload identity tests by passing in app name.
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  tekton/templates/tasks/kf-ready-task.yaml
Labels: approved, cla: yes, lgtm, size/S

#730 notebook tests need to use a unique subdirectory
  images/latest_image.json
  py/kubeflow/testing/notebook_tests/execute_notebook.py
  tekton/templates/pipelines/kustomization.yaml
  tekton/templates/pipelines/test-pod.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/M

#732 Setup a kf-ci-dev namespace for manual sync'ing of Tekton pipelines.
  Makefile
  acm-repos/kf-ci-v1/namespaces/auto-deploy/apps_v1_statefulset_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/auto-deploy/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/apps_v1_statefulset_test-pod.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_cleanup-kubeflow-ci.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_deploy-gcp-blueprint.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_golang-test.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_iap-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_kf-ready.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_nb-tests.yaml
  acm-repos/kf-ci-v1/namespaces/kf-ci/tekton.dev_v1alpha1_task_notebook-test-builder.yaml
  docs/tekton.md
  images/Dockerfile.py3
  images/latest_image.json
  tekton/templates/installs/kf-ci-dev/kustomization.yaml
  tekton/templates/installs/kf-ci-dev/service-account-kf-ci.yaml
  tekton/templates/pipelines/test-pod.yaml
  tekton/templates/tasks/cleanup-kubeflow-ci.yaml
  tekton/templates/tasks/deploy-gcp-blueprint.yaml
  tekton/templates/tasks/gcp-iap-endpoint-ready-task.yaml
  tekton/templates/tasks/go-tests.yaml
  tekton/templates/tasks/kf-ready-task.yaml
  tekton/templates/tasks/notebook-test-task.yaml
Labels: approved, cla: yes, lgtm, size/L

#740 Update deploy script to work with Kptfile refactor.
  py/kubeflow/testing/create_kf_from_gcp_blueprint.py
Labels: approved, cla: yes, lgtm, size/S

#741 chore: add cla yes and no labels for googlebot
  label_sync/kubeflow_label.yml
Labels: approved, cla: yes, lgtm, size/XS

#734 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS
