Repository kubeflow/testing, pull requests merged in 2020-02, with the labels that each got.

#596 Create a script to make updating application resources easier.
  py/kubeflow/testing/tools/applications.py
Labels: approved, lgtm, size/M

#597 update default pattern to match new convention
  py/kubeflow/testing/get_kf_testing_cluster.py
Labels: approved, lgtm, size/XS

#599 Coerce versions to strings
  py/kubeflow/testing/tools/applications.py
Labels: approved, lgtm, size/XS

#589 Add a script to troubleshoot failed deployments
  README.md
  py/kubeflow/testing/troubleshoot_deployment.py
Labels: approved, lgtm, size/M

#598 [Node][License] `concatenate_license` added. Addressed bugfixes
  py/kubeflow/testing/node-license-tools/commands/concatenateLicense.js
  py/kubeflow/testing/node-license-tools/commands/getLicenseInfo.js
  py/kubeflow/testing/node-license-tools/node_lic.js
  py/kubeflow/testing/node-license-tools/package.json
Labels: approved, area/front-end, area/testing, kind/feature, lgtm, priority/p0, size/M

#602 Get email only in create_unique_kf_instance
  py/kubeflow/testing/create_unique_kf_instance.py
Labels: approved, lgtm, size/XS

#604 Reconciler for autodeployments
  py/kubeflow/testing/assertions.py
  py/kubeflow/testing/auto_deploy/README.md
  py/kubeflow/testing/auto_deploy/__init__.py
  py/kubeflow/testing/auto_deploy/reconciler.py
  py/kubeflow/testing/auto_deploy/reconciler_test.py
  py/kubeflow/testing/auto_deploy/test_data/deployments.yaml
  py/kubeflow/testing/auto_deploy/util.py
  py/kubeflow/testing/gcp_util.py
  py/kubeflow/testing/git_repo_manager.py
  py/kubeflow/testing/git_repo_manager_test.py
Labels: approved, lgtm, size/XXL

#606 Create a python3.8 version of the worker image
  images/Dockerfile
  images/Dockerfile.py3
  images/manifest/README.md
  images/manifest/kustomization.yaml
  images/manifest/statefulset.yaml
  images/skaffold.yaml
Labels: approved, lgtm, size/L

#612 * Update cleanup_ci to match regexes for new autodeployed clusters
  py/kubeflow/testing/cleanup_ci.py
Labels: approved, lgtm, size/S

#610 Server for AutoDeploy v2
  py/kubeflow/testing/auto_deploy/__init__.py
  py/kubeflow/testing/auto_deploy/reconciler.py
  py/kubeflow/testing/auto_deploy/server.py
  py/kubeflow/testing/auto_deploy/util.py
  test-infra/auto-deploy/templates/index.html
Labels: approved, lgtm, size/L

#591 Auto Deploy V2
  .gitignore
  playbook.md
  py/kubeflow/testing/auto_deploy/server.py
  py/kubeflow/testing/cd/update_kf_apps.py
  py/kubeflow/testing/cleanup_ci_test.py
  py/kubeflow/testing/create_unique_kf_instance.py
  test-infra/auto-deploy/Dockerfile
  test-infra/auto-deploy/Dockerfile.skaffold
  test-infra/auto-deploy/Makefile
  test-infra/auto-deploy/Pipfile
  test-infra/auto-deploy/Pipfile.lock
  test-infra/auto-deploy/auto_deploy.sh
  test-infra/auto-deploy/checkout_lib/__init__.py
  test-infra/auto-deploy/checkout_lib/checkout_util.py
  test-infra/auto-deploy/checkout_lib/repo_clone_snapshot.py
  test-infra/auto-deploy/checkout_lib/snapshot_kf_deployment.py
  test-infra/auto-deploy/manifest/config/deploy-kubeflow.yaml
  test-infra/auto-deploy/manifest/config/deployments.yaml
  test-infra/auto-deploy/manifest/deployment.yaml
  test-infra/auto-deploy/manifest/kustomization.yaml
  test-infra/auto-deploy/manifest/service.yaml
  test-infra/auto-deploy/manifest/virtual_service.yaml
  test-infra/auto-deploy/requirements.txt
  test-infra/auto-deploy/skaffold.yaml
Labels: approved, lgtm, size/XXL

#615 Fix py3 test worker
  images/Dockerfile.py3
Labels: approved, lgtm, size/S
