Repository kubeflow/testing, pull requests merged in 2021-02, with the labels that each got.

#866 Add tekton tasks for eks-cluster-create/teardown and kaniko
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/eks-cluster-create.yaml
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/eks-cluster-teardown.yaml
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/eks-cluster-create.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/eks-cluster-teardown.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/secret.yaml
Labels: approved, cla: yes, lgtm, size/L

#886 Roll back self-managed repo test
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/secret.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#888 Fix godoc parsing for go license script
  py/kubeflow/testing/go-license-tools/get_github_repo.py
Labels: approved, cla: yes, lgtm, size/S

#865 Update optional-test-infra doc
  README.md
  aws-images/Makefile
  aws-images/README.md
  aws/Access/README.md
  aws/Access/console-access/infra-admin/infra-admin.yaml
  aws/Doc/architecture.md
  aws/Doc/argo_e2e.md
  aws/Doc/onboarding.md
  aws/Doc/setup-infra.md
  aws/Picture/OptionalTestInfra_CurrentDesign.png
  aws/Picture/OptionalTestInfra_FutureDesign.png
  aws/README.md
  gcp_README.md
  images/Dockerfile.py3.aws
Labels: approved, cla: yes, size/XXL

#889 Fix formatting
  README.md
Labels: approved, cla: yes, size/XS

#890 Add * instead of number
  README.md
Labels: approved, cla: yes, size/XS

#891 add theofpa as infra-viewer
  aws/Access/assume-role-access/infra-viewer/trust-policy.json
Labels: approved, cla: yes, lgtm, size/XS

#892 Migrate tf-operator to new test-infra
  aws/Access/README.md
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#894 Remove old test-infra
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/Makefile
  aws/User/clusters/kubeflow-shared-test-infra-poc-argo/namespaces/argo/installs/argo-starter.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-pipelines/installs/tekton-pipelines-starter.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/tf-operator-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/installs/prow-starter.yaml
Labels: approved, cla: yes, size/XXL

#895 Remove unnecessary tekton tasks
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/echo-helloworld.yaml
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/secret.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/echo-helloworld.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/secret.yaml
Labels: approved, cla: yes, size/M

#899 [AWS] Improve self-check process
  .github/pull_request_template.md
  aws/Makefile
Labels: approved, cla: yes, size/M

#898 Add kubeflow/kubeflow to prow's presubmits
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#902 [AWS] Add test lifecycle
  aws/Picture/TestLifeCycle.png
  aws/README.md
Labels: approved, cla: yes, lgtm, size/XS

#901 Kaniko cache
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml
Labels: approved, cla: yes, lgtm, size/S

#906 update kaniko image to the official
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/kaniko.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/kaniko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#903 [AWS] Add IaC support
  aws/IaC/CDK/test-infra/.gitignore
  aws/IaC/CDK/test-infra/README.md
  aws/IaC/CDK/test-infra/app.py
  aws/IaC/CDK/test-infra/cdk.context.json
  aws/IaC/CDK/test-infra/cdk.json
  aws/IaC/CDK/test-infra/config/static_config/ACM_Resources.py
  aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
  aws/IaC/CDK/test-infra/config/static_config/EKS_Resources.py
  aws/IaC/CDK/test-infra/config/static_config/IAM_Resources.py
  aws/IaC/CDK/test-infra/config/static_config/S3_Resources.py
  aws/IaC/CDK/test-infra/requirements.txt
  aws/IaC/CDK/test-infra/setup.py
  aws/IaC/CDK/test-infra/source.bat
  aws/IaC/CDK/test-infra/test_infra/__init__.py
  aws/IaC/CDK/test-infra/test_infra/test_infra_stack.py
  aws/README.md
Labels: approved, cla: yes, lgtm, size/L

#907 changed from staging proxy to production proxy of proxy agent
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml
Labels: approved, cla: yes, lgtm, size/S

#908 chore: Update OWNERS, add new team members
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#909 updated kfp endpoint to production
  test-infra/kfp/endpoint
Labels: approved, cla: yes, lgtm, size/XS

#910 test(kfp): add access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com
  acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
  test-infra/kfp/iam/iam.yaml
Labels: approved, cla: yes, lgtm, size/S

#911 changed back to staging proxy
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/proxy-agent-patch.yaml
Labels: approved, cla: yes, lgtm, size/S

#912 updated endpoint back to staging
  test-infra/kfp/endpoint
Labels: approved, cla: yes, lgtm, size/XS

#913 update owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#914 test(kfp): change access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com
  acm-repos/kf-ci-management/namespaces/kfp-ci/iam.yaml
  test-infra/kfp/iam/iam.yaml
Labels: approved, cla: yes, lgtm, size/S

#917 Remove environment variable logs
  py/kubeflow/testing/util.py
Labels: approved, cla: yes, size/XS
