Repository kubeflow/testing, pull requests merged in 2021-01, with the labels that each got.

#843 Test for organization webhook
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/XS

#844 Rever PR #843
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/XS

#845 Fix one unnecessary item in PR template
  .github/pull_request_template.md
Labels: cla: yes, size/XS

#850 chore(gcp): migrate to use e2 machines
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containercluster_code-intelligence.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containernodepool_code-intelligence-cpu-pool-v1.yaml
Labels: approved, cla: yes, size/S

#852 chore(gcp): migrate to e2 machine type attemp 2
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containercluster_code-intelligence.yaml
  acm-repos/kf-ci-management/namespaces/issue-label-bot-dev/container.cnrm.cloud.google.com_v1beta1_containernodepool_code-intelligence-cpu-pool-v1.yaml
Labels: approved, cla: yes, size/S

#849 Update onboarding doc
  aws/Doc/onboarding.md
Labels: approved, cla: yes, lgtm, size/XS

#857 test(gcp): set up GSA workload identity for test pods in kf-ci-v1 cluster
  Makefile
  acm-repos/kf-ci-v1/namespaces/test-pods/namespace.yaml
  acm-repos/kf-ci-v1/namespaces/test-pods/v1_serviceaccount_default.yaml
  test-infra/kf-ci-v1/gcp_config/Makefile
  test-infra/kf-ci-v1/gcp_config/cluster.jinja
  test-infra/kf-ci-v1/test-pods/kustomization.yaml
  test-infra/kf-ci-v1/test-pods/namespace.yaml
  test-infra/kf-ci-v1/test-pods/service-account.yaml
Labels: approved, cla: yes, size/M

#858 Use repo-level trigger plugins
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#842 Add tf operator presubmit to share test infra config
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/tf-operator-repo.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/pipelineresources/tf-operator-repo.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#860 Validate if argocd works
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc-tekton/namespaces/tekton-templates/tf-operator-repo.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/S

#862 Increase echo-test from 1d to 1s
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#863 Decrease echo-test from 1s to 1d
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#859 Add myself into OWNERS
  OWNERS
Labels: cla: yes, lgtm, size/XS

#864 Add optional-test-infra-tekton resources
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/echo-helloworld.yaml
  aws/Makefile
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-tekton/namespaces/kubeflow-test-infra/task/echo-helloworld.yaml
Labels: approved, cla: yes, size/M

#867 Migrate Pytorch-operator
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#868 Disable pytorch in old test-infra
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#869 Fix typo
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/XS

#870 Enable pytorch
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#871 Set aws_argo_cluster_endpoint read from command-line parameter
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, cla: yes, size/S

#872 Revert #871
  py/kubeflow/testing/run_e2e_workflow.py
Labels: approved, cla: yes, size/XS

#873 Use pre-built image for experimenting
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#874 Update to latest image
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#875 Migrate kubeflow/manifests
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#876 Migrate kfctl repo
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#877 Migrate katib repo
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#878 Migrate kubeflow/kubeflow repo
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/S

#879 Migrate xgboost-operator repo
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#880 Add access related resources
  aws/Access/README.md
  aws/Access/assume-role-access/infra-editor/trust-policy.json
  aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
  aws/Makefile
  aws/README.md
  aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/L

#881 Migrate KFServing to new test-infra
  aws-images/daily-worker/Dockerfile
  aws-images/daily-worker/update-iam-assume-role-policy.sh
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#882 Update daily worker config
  aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/M

#883 Create periodic job for infra-viewer access sync
  aws/Access/assume-role-access/infra-viewer/trust-policy.json
  aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/M

#884 Use self-managed organzation for kfserving tests
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/config.yaml
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/config.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/M

#885 Fix typo
  aws/GitOps/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/plugins.yaml
  aws/User/clusters/kubeflow-shared-test-infra-poc/namespaces/prow/configmap/plugins.yaml
Labels: approved, cla: yes, size/XS
