Repository kubeflow/testing, pull requests merged in 2021-03, with the labels that each got.

#918 Add unit test for python files
  .gitignore
  py/kubeflow/testing/cloudprovider/aws/prow_artifacts.py
  py/kubeflow/testing/cloudprovider/aws/requirements.txt
  py/kubeflow/testing/cloudprovider/aws/test_util.py
  py/kubeflow/testing/cloudprovider/aws/util.py
Labels: approved, cla: yes, size/XL

#923 Add Katib images to private ECR
  aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Labels: approved, cla: yes, lgtm, size/S

#924 Fix formatting issue
  aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py
Labels: approved, cla: yes, lgtm, size/M

#925 Migrate kubeflow/testing to optional-test-infra
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/plugins.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/plugins.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#926 Add kubeflow/kubeflow postsubmit job
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#927 Add periodic prowjobs for aws IAM role sync
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/M

#928 Disable daily-worker
  aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/M

#929 Add tf-operator postsubmit test
  aws/GitOps/clusters/optional-test-infra-daily-worker/namespaces/prow/config.yaml
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/Makefile
  aws/User/clusters/optional-test-infra-daily-worker/namespaces/prow/configmap/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/L

#934 test(gcp): add storage object admin permission to kfp-standalone-1-vm GSA
  acm-repos/kf-ci-management/namespaces/kfp-ci/iam.cnrm.cloud.google.com_v1beta1_iampolicymember_vm-cloud-storage-object-admin.yaml
  test-infra/kfp/kfp-standalone-1/instance/iam.yaml
  test-infra/kfp/kfp-standalone-1/instance/kustomization.yaml
Labels: approved, cla: yes, size/M

#935 test(gcp): expand kfp-ci oauth2 scope to cloud-platform
  acm-repos/kf-ci-management/namespaces/kfp-ci/container.cnrm.cloud.google.com_v1beta1_containernodepool_kfp-standalone-1-nodepool-v2.yaml
  test-infra/kfp/kfp-standalone-1/.krmignore
  test-infra/kfp/kfp-standalone-1/Kptfile
  test-infra/kfp/kfp-standalone-1/configsync/config-management-operator.yaml
  test-infra/kfp/kfp-standalone-1/instance/nodepool-patch.yaml
  test-infra/kfp/kfp-standalone-1/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/upstream/cluster.yaml
Labels: approved, cla: yes, size/M

#936 aws optional-test-infra: Enable tests for v1.3-branch of kubeflow/kubeflow
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#938 Add PULL_BASE_REF for checking out repos
  images/checkout_repos.sh
Labels: approved, cla: yes, size/XS

#939 [Follow Up] Add PULL_BASE_REF for checking out repos
  images/checkout_repos.sh
Labels: approved, cla: yes, size/XS

#941 Fix postsubmit PR link
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#942 [FollowUp] Fix postsubmit PR link
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, size/XS

#943 Allow test on Katib release-0.11 branch
  aws/GitOps/clusters/optional-test-infra-prow/namespaces/prow/config.yaml
  aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml
Labels: approved, cla: yes, lgtm, size/XS
