Repository kubeflow/testing, pull requests merged in 2022-02, with the labels that each got.

#981 test(kfp): update kfp-all.yaml
  acm-repos/kfp-standalone-1/kfp-all.yaml
Labels: lgtm, size/XL, approved

#982 kfp: Set memory limit only for mysql
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/mysql-patch.yaml
Labels: size/S, lgtm, approved

#983 KFP: Remove status from kfp-standalone-1 manifest
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/limit-range.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/status-deletion.yaml
Labels: lgtm, size/XL, approved

#984 test(kfp): Upgrade to 1.8.0-rc.2
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, size/XL, approved

#987 pipelines: remove status by running kfp-update
  acm-repos/kfp-standalone-1/kfp-all.yaml
Labels: lgtm, size/XL, approved

#988 test(kfp): Upgrade to 1.8.0-rc.3
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: size/M, lgtm, approved

#990 test(kfp): Upgrade to 1.8.0
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: size/M, lgtm, approved
