Repository kubeflow/testing, pull requests merged in 2022-04, with the labels that each got.

#996 test(kfp): Upgrade to 2.0.0-alpha.1
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/Makefile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/Kptfile
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache-deployer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/cache/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/installs/generic/pipeline-install-config.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/metadata/base/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/base/pipeline/metadata-writer/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: size/M, lgtm, approved

#997 kfp: increase memory limit for metadata-grpc-deployment
  acm-repos/kfp-standalone-1/kfp-all.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/kustomization.yaml
  test-infra/kfp/kfp-standalone-1/kustomize/instance/metadata-grpc-deployment-patch.yaml
Labels: size/S, lgtm, approved

#989 chore(kfp): update instructions for updating kfp deployment in the test cluster.
  test-infra/kfp/README.md
Labels: size/S, lgtm, approved

#998 update eks kubernetes version to 1.19
  images/aws-scripts/create-eks-cluster.sh
Labels: size/XS, lgtm, approved
